### ISSUE TITLE
Cannot generate a non-breaking space in output for Word

### ISSUE THREAD

**Issue by matth82** [dradis/dradis-ce#1080]
### Steps to reproduce

Cannot generate a non-breaking space in output for Word.

### Expected behavior
A non-breaking space should be inserted preventing breaking up two words that should be together on one line.

### Actual behavior
Is not possible.

### System configuration
**Dradis version**:
Dradis Professional Edition v4.4.1

**Ruby version**:

**OS version**:
Ubuntu (Firefox)

**Comment by rachkor** [comment]
@matth82 would you be able to email this to our support team or post it in Slack? This is the GitHub repo for our Community Edition that doesn't have Word reporting. If you can give us more details, maybe steps to replicate, I'd be happy to investigate!
