### ISSUE TITLE
Merge service-related scanner output

### ISSUE THREAD

**Issue by leesoh** [dradis/dradis-ce#118]
### Steps to reproduce
I've tested this with Nessus and Qualys. Import scanner output into Dradis.

### Expected behavior
Both of the above scanners include an issue that describes the results of the port scan. In a perfect world, Dradis would treat all port-scan related issues as the same and parse this data into a node service entry.

### Actual behavior
Qualys port scans are removed from All Issues and imported as expected.
![2017-05-02-image-003](https://cloud.githubusercontent.com/assets/1276654/25628855/f1b44032-2f24-11e7-94d4-43288da4e59b.png)

Nessus port scans are treated as an issue.
![2017-05-02-image-004](https://cloud.githubusercontent.com/assets/1276654/25628884/0730bfbc-2f25-11e7-8354-549648e772ac.png)

The output of both scanners is combined at the node level, but is duplicated.
![2017-05-02-image-002](https://cloud.githubusercontent.com/assets/1276654/25628906/140f6ed6-2f25-11e7-8180-ca9b304d8a85.png)

### System configuration
**Dradis version**: Dradis Pro 2.6

**Ruby version**:

**OS version**:

**Comment by leesoh** [comment]
I believe the Qualys strangeness will be resolved with https://github.com/dradis/dradis-qualys/pull/7.

**Comment by etdsoft** [comment]
Implemented, ships in the next release.

See https://github.com/dradis/dradis-ce/pull/222
