### ISSUE TITLE
Enhancement Request: Delete multiple items of evidence in one go

### ISSUE THREAD

**Issue by Kalaratri** [dradis/dradis-ce#123]
Currently when running vulnerability scans, particularly amalgamated from numerous tools a host can end up with a LARGE amount of issues. 

When compiling the penetration test report it is essential to only report the issues that led to the compromise, so all other vulnerabilities must be deleted from the host.

This is a very time consuming process doing them one at a time.  It would be great to have a select all checkbox and an ability to reverse any selections before deleting all in one go. Literally sometime I'll spend 20-30 minutes deleting irrelevant evidence under a host.

**Comment by dormi** [comment]
@Kalaratri thanks for sending this over.
An improved evidence view seems to be gaining priority.

**Comment by Kalaratri** [comment]
No worries, would be a welcome addition and in fact could apply to any object. It would be equally helpful to be able to delete notes in a similar manner..

**Comment by etdsoft** [comment]
This was implemented and shipped in v2.9
