### ISSUE TITLE
Enhancement Request - Smarter Filtering

### ISSUE THREAD

**Issue by Kalaratri** [dradis/dradis-ce#124]
When searching amongst issues it would be great to be able to filter all critical issues for example. At the moment when using a search term "critical" the results also include any record with the word "critical", whether it's tagged critical or not. 

This would be a great workflow feature that would help initially target high risk vulnerabilities first...

**Comment by leesoh** [comment]
Seconded. Either filters on columns, or some sort of query language (Tag|Critical & Title: *SQL*)

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
