### ISSUE TITLE
NoMethodError in Search#Index

### ISSUE THREAD

**Issue by Kalaratri** [dradis/dradis-ce#125]
### Steps to reproduce

Help us help you, how can we reproduce the problem?

I'm searching for the phrase windows_privesc_check which results in a new error:

### Expected behavior
Search results displayed

### Actual behavior
Error:

![screen shot 2017-05-13 at 11 13 34 am](https://cloud.githubusercontent.com/assets/26086418/26031788/cba20ae0-3880-11e7-9fce-9f6a805e425d.png)

### System configuration
**Dradis version**:
3.6

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]

**OS version**:
Linux kali 4.6.0-kali1-686 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux

**Comment by etdsoft** [comment]
I seem to be able to run this search without problems, for an Issue with this content:

```
#[Title]#

Issue 61

#[Type]#
windows_privesc_check
```

Please feel  free to re-post with more steps to reproduce.
