### ISSUE TITLE
Search Icon Disappears Regularly

### ISSUE THREAD

**Issue by Kalaratri** [dradis/dradis-ce#126]
### Steps to reproduce
A little difficult to get it to reproduce reliably; it's a sporadic issue that happens many times a day.

Help us help you, how can we reproduce the problem?

### Expected behaviors
Search Icon should be available

### Actual behaviors
Search Icon disappaers, a page refresh will resolve the issue

### System configuration
**Dradis version**:
3.6

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]

**OS version**:
Linux kali 4.6.0-kali1-686 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux

**Comment by rachkor** [comment]
@Kalaratri we haven't had any other reports of this but would love to fix if we can figure out a way to reproduce. Can you keep an eye out and update us when you're able to reproduce?

**Comment by Kalaratri** [comment]
Sure, I'll be back into it tomorrow....

**Comment by Kalaratri** [comment]
I rebooted everything, obviously restarted all services, firefox etc and spent the last couple of days trying to reproduce this, but it's not happened since, so looks like a local issue that's now resolved :). Closing.
