### ISSUE TITLE
Add References and Plugin_ID Fields to Burp Plugin Manager

### ISSUE THREAD

**Issue by leesoh** [dradis/dradis-ce#128]
### Steps to reproduce
1. Import Burp Data
2. Lament the missing fields

### Expected behavior
The <issue><type>1234</type>... field would be exposed as plugin_id.

The <issue><references>http://blah</references>... field would be exposed as references.

### Actual behavior
Nothing!

### System configuration
**Dradis version**: 2.6

**Ruby version**:

**OS version**:

**Comment by rachkor** [comment]
@leesoh, could you provide a sample file that contains the `<references>` field? I think our Burp sample files are older as I'm not seeing anything that we could import as the references.
