### ISSUE TITLE
Enhancement Request - Search Result Improvement

### ISSUE THREAD

**Issue by Kalaratri** [dradis/dradis-ce#129]
I LOVE the search feature! I use it all the time to lookup a reference to a name or an IP that you know you've seen somewhere, but can't remember where!

I also use it a lot to search for a previously issued and documented command. You know, you can remember most of it, but not the full syntax... 

The results page shows the context of the results but the search term is always the Last part of the results. So it's necessary to click on the link to drill down. A great workflow improvement would be to include some characters after the phrase is found too, maybe 30-50 chars and not so many before. This way we can search and then copy the command straight from the search results rather than drilling down.

What do you think?

**Comment by rachkor** [comment]
@Kalaratri I think this was implemented several releases ago but the ticket was never closed! Check out the docs here for the pro version (same UI): https://dradisframework.com/pro/support/guides/projects/project_search.html. If I'm misunderstanding the request, let me know!
