### ISSUE TITLE
Enhancement Request - Suppress Hosts / Folders from Report

### ISSUE THREAD

**Issue by Kalaratri** [dradis/dradis-ce#130]
Currently all hosts with evidence are included in the HTML report. This is fine for compromised hosts with penetration evidence. We even have the ability to include notes for a host and change the category to allow the notes to be included in the report or not.

In many cases there are hosts in the database that have a wealth of evidence generated against them from automated tools. It may be the pentester has yet to review these hosts and needs to produce an interim report. Or perhaps they were never compromised.

Rather than deleting the entire host it would be great to be able to exclude a host or a folder from the generated report.

I am currently needing to produce an interim report that will require extensive cleanup to remove all of the details of the hosts yet to be manually compromised, yet have evidence from plugins....

**Comment by leesoh** [comment]
I've wanted something similar to this to mark the hosts I've reviewed. Maybe a host status that would go from New-Reviewed-Report?

**Comment by Watchyourbackz** [comment]
I was looking for the very option. It would be nice to take certain tool plugin imports and move the results you desire to include in reports into a separate folder, and have the report template to call on those specific folders.

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future. Thanks very much for the discussion here, everyone!
