### ISSUE TITLE
Dradis on Kali won't setup properly 

### ISSUE THREAD

**Issue by Phexcom** [dradis/dradis-ce#131]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up dradis (3.6.0-0kali1) ...
Warning: The home dir /var/lib/dradis you specified already exists.
The system user `dradis' already exists. Exiting.
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from require at /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:91)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from require at /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:91)
Faraday::Builder is now Faraday::RackBuilder.
Rails Error: Unable to access log file. Please ensure that /usr/lib/dradis/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /usr/lib/dradis/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at /usr/lib/dradis/config/environment.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at /usr/lib/dradis/config/environment.rb:5)
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/lib/dradis/log/resque.log
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
dpkg: error processing package dradis (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of kali-linux-full:
 kali-linux-full depends on dradis; however:
  Package dradis is not configured yet.

dpkg: error processing package kali-linux-full (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of kali-linux-all:
 kali-linux-all depends on kali-linux-full; however:
  Package kali-linux-full is not configured yet.

dpkg: error processing package kali-linux-all (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dradis
 kali-linux-full
 kali-linux-all
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by rachkor** [comment]
Hey @Phexcom, I think this is the same error reported in the forums here: http://discuss.dradisframework.org/t/error-processing-package-dradis/454

Could you try installing from git in another folder? E.g. `/opt/dradis-ce/` instead?
Here's our Kali install guide for reference:  https://dradisframework.com/ce/documentation/install_kali.html
