### ISSUE TITLE
Dependencies specification

### ISSUE THREAD

**Issue by Yamakaky** [dradis/dradis-ce#132]
Could you add a list of the required dependencies in the readme? It not very convenient to do trial and error.

**Comment by rachkor** [comment]
@Yamakaky, Rachael with the Dradis support team here. Have you checked out the git install guide here? https://dradisframework.com/ce/documentation/install_git.html There is a link to the Kali dependencies section and should cover any common problems that come up during install.

**Comment by Yamakaky** [comment]
Oh, right. It should be directly in the readme since it's Debian specific and not only Kali.

**Comment by etdsoft** [comment]
closing as this isn't a bug for the tracker, feel free to post in the forum
