### ISSUE TITLE
Embed images in HTML report

### ISSUE THREAD

**Issue by Yamakaky** [dradis/dradis-ce#133]
Currently, when exporting an HTML report, the images added using the !URL! syntax use a relative URL. It means that if someone saves the webpage for later view, none of the images will load. To fix that, the export could inline the images in base64.

**Comment by rachkor** [comment]
@Yamakaky I am looking into this and not able to replicate. Can you clarify? Here's what I did: 

1. Added several images to a Dradis CE project with the `!URL!` syntax
2. Exported the project to HTML
3. Saved the page as HTML for later viewing
4. Shut down my Dradis CE server
5. Opened the saved HTML page and confirmed that the images display as expected. 

Closing for now as this appears to not be an issue right now. Let me know if I'm misunderstanding the situation!
