### ISSUE TITLE
Update the Qualys plugin to include the NBHOST details

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#142]
The Qualys plugin currently doesn't import the `<KEY value="NBHOST_ALIVE">` or `<KEY value="NBHOST_TOTAL">` values from the XML file. Example: https://github.com/dradis/dradis-qualys/blob/master/spec/fixtures/files/two_hosts_common_issue.xml#L14

We could create Notes (example: https://github.com/dradis/dradis-nessus/blob/14420045f6c2f912693ff3d77cf821a48aa55b7e/lib/dradis/plugins/nessus/importer.rb#L89) and pull this in as a field (with the Plugin Manager configuration option). 

Or we could pull this in as a Node property (example: https://github.com/dradis/dradis-nessus/blob/14420045f6c2f912693ff3d77cf821a48aa55b7e/lib/dradis/plugins/nessus/importer.rb#L55). 

Originally requested by Austin

**Comment by MattBudz** [comment]
closed due to inactivity
