### ISSUE TITLE
Importing MediaWiki issues 

### ISSUE THREAD

**Issue by ChriZzn** [dradis/dradis-ce#146]
**NameError in IssuesController#import** 

_uninitialized constant Dradis::Plugins::Mediawiki::Filters::FullTextSearch::Net_

        @filter.run(@params)
      elsif @filter.respond_to?(:query)
        @filter.query(@params)
      end
    else
      [{

I get this error when I try to search issues from Mediawiki.

I'm using the latest Version of dradis-ce and Mediawiki.

**Comment by dormi** [comment]
Thanks for reporting this @ChriZzn

**Comment by ChriZzn** [comment]
So i got another Problem: "This query yielded no results."

I couldn't Import any Issue from MediaWiki but if i search in the Mediawiki API manually i get results.
