### ISSUE TITLE
Very Large Projects Can't Be Deleted in GUI

### ISSUE THREAD

**Issue by leesoh** [dradis/dradis-ce#147]
### Steps to reproduce
1. Create a massive project (I had ~180 endpoints, authenticated VA, about 180 unique issues spread across those hosts)
2. Try to delete
3. Shake your fist at the heavens

### Expected behavior
Project should delete

### Actual behavior
Project does not delete and instead returns a 404. Can be deleted using the GUI. For a rough metric, GUI method takes about a minute.

### System configuration
**Dradis version**: Dradis Pro 2.7, appliance.

**Ruby version**: 

**OS version**:

**Comment by etdsoft** [comment]
Implemented, ships in the next release.
