### ISSUE TITLE
Enhancement Request - Adding Nessus CVSSv3 fields

### ISSUE THREAD

**Issue by Rannie18** [dradis/dradis-ce#157]
### Steps to reproduce
Help us help you, how can we reproduce the problem?

Nessus files provide CVSSv3 vector scores (<cvss3_vector>) for some of their plugins, however it is not an available field within Dradis.

### Expected behavior
Tell us what should happen

We would like to see CVSSv3 Vector Scores as an available field to include in our reports.

### Actual behavior
Tell us what happens instead

While the nessus files contain the <cvss3_vector> tags, we are unable to utilize the CVSSv3 vector scores as a field.

### System configuration
**Dradis version**:
Dradis Professional Edition v2.6.0

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

**OS version**:
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.51-1

**Comment by rachkor** [comment]
Update the Nessus plugin to include both `report_item.cvss3_base_score` and `report_item.cvss3_vector` as available fields.
