### ISSUE TITLE
Verbose Error Messages with Password Reset

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#159]
### Steps to reproduce
On the login page, request a password reset.

### Actual behavior
If the mail server is not configured, a verbose error message is displayed. 

### Workaround
Set up the mail server using these instructions: https://dradisframework.com/pro/support/guides/customization/mail_server.html

### System configuration
**Dradis version**: Pro v2.7.0

Issue originally reported by Joel

**Comment by MattBudz** [comment]
closed due to inactivity
