### ISSUE TITLE
How to add word export

### ISSUE THREAD

**Issue by habibiefaried** [dradis/dradis-ce#16]
Hi folks, I wanna ask something
I want to add (https://github.com/dradis/dradis-word_export) to my dradis-ce (https://github.com/dradis/dradis-ce) because only XML and HTML export report available.

How to do that?

Thanks

--Habibie

**Comment by etdsoft** [comment]
Hi @habibiefaried,

Unfortunately the `dradis-word_export` repo is 4 years old, and it worked before Microsoft was forced to made some changes into the inner workings of the Word document format. These days Dradis CE doesn't have a Word add-on.

Maybe the [dradis-pdf_export](https://github.com/dradis/dradis-pdf_export) can be of use, or maybe HTML and then use the browser to print to PDF?

**Comment by habibiefaried** [comment]
Hi, i used that dradis pdf too and dependency problem.
Thanks for your answer
