### ISSUE TITLE
Currently Captions do not flow with Image in word reports

### ISSUE THREAD

**Issue by dormi** [dradis/dradis-ce#162]
### Steps to reproduce
Generate a word report with an image and a caption.

### Expected behavior
Image and caption should not be separable.

### Actual behavior
Currently Captions do not flow with Images, in some cases the captions for Images go to the next page instead of sticking with the images

### Workaround
Edit the word file manually. In Word this is normally achieved by Word Paragraph Formatting - Keep with Next

---

This issue was reported by Rahul.

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future. Note that this can be resolved post-export with a macro if required.
