### ISSUE TITLE
Evidence content field is disabled

### ISSUE THREAD

**Issue by schrnz** [dradis/dradis-ce#166]
### Steps to reproduce

1. Open an issue (< baseUrl>/issues/< issueID>)
2. Switch to "Evidence" tab
3. Click on "Add new"

### Expected behavior
The text field under "New evidence content"  is activated and writable.

### Actual behavior
The text field under "New evidence content" is deactivated. In order to write the evidence content, you need to save the empty evidence, click on edit, and then the text field is enabled. 

### System configuration
**Dradis version**:
3.8.0

**Ruby version**:
ruby 2.3.3p222

**OS version**:
Raspbian 9

**Comment by rachkor** [comment]
@schrnz, thanks for submitting this feature request. Just to clarify, this is the expected behavior with the current version of Dradis: https://dradisframework.com/pro/support/guides/projects/issues.html#evidence-issue.

**Comment by schrnz** [comment]
Ok I see... anyway, you are right, in this case this is not a bug report but a feature request =)
I would still keep this around since the behavior described above seems a bit odd to me from a usability perspective. I guess the idea is to preview the structure of whatever is chosen in the drop-down menu? But I can imagine that almost always you want to have content in your evidence and hence allowing to write it down during creation saves time and is more intuitive.

**Comment by rachkor** [comment]
Closing, added this feature request to our internal idea backlog to investigate adding in the future!
