### ISSUE TITLE
Hyperlinks: parenthesis disappear, colons duplicated

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#174]
### Steps to reproduce

1. When a link includes brackets, they don't show up in the text. The link target is still correct.
The parentheses are being interpreted as URL's :title. Inquiring upstream for a workaround:
https://jgarber.lighthouseapp.com/projects/13054-redcloth/tickets/279-links-with-a-name-that-contains-a-trailing-whatever

2. If there is a colon after the link, it is duplicated in the report.
Also seems to be caused by the upstream parser that decides on purpose to leave railing : out of the link. So what we see is the one that is left outside but also the one that's coming from the link's text.
https://github.com/jgarber/redcloth/blob/master/spec/fixtures/links.yml#L179-L183

```
#[Description]#
https://test.com?alert(document.domain)
https://test.com?double_colon:
```

### Expected behavior
Links would export into the report like: 

```
https://test.com?alert(document.domain)
https://test.com?double_colon:
```

### Actual behavior
Links export into the report like: 

```
https://test.com?alert
https://test.com?double_colon::
```

Originally reported by Jarmo.

**Comment by MattBudz** [comment]
closed due to inactivity
