### ISSUE TITLE
Evidence in Nodes in word reports don't work properly

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#175]
### Steps to reproduce

When in a word report template we use a structure like this one:
`Node > Issue > Evidence`
the report is populated with all Evidence for that Issue, not only the ones that relate the Issue to the Node.

That may be understood as the Issue is forcing its own scope.
But if I want to just check all evidence for that Node and I try:
`Node > Evidence`
this seems to provide an empty list of Evidence.

### System configuration
**Dradis version**: v2.8.1

Thank you @kulisu for reporting this

**Comment by rachkor** [comment]
Closed, fix shipped in v2.9.0

**Comment by etdsoft** [comment]
@rachkor in cases such as this, we'd also add the Milesone
