### ISSUE TITLE
Quotation marks do not export

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#176]
Quotation marks do not export correctly into reports.

### Steps to reproduce
Example content in Dradis:
```
#[Description]#
Quotation marks "disappear" from text
```

### Expected behavior
Should export into the Word report as:
```
Quotation marks "disappear" from text
```
### Actual behavior
Exports into the Word report as:
```
Quotation marks disappear from text
```

Bug initially reported by Jarmo

**Comment by njfox** [comment]
Has there been any progress on this issue? We use quotation marks in several of our Issue writeups and currently we are having to manually find and update every instance of this after exporting the report.

**Comment by MrJester** [comment]
Ya this is a pretty big issue for our reports as well.

**Comment by etdsoft** [comment]
Understood, we're looking into this atm, watch this space!

**Comment by dormi** [comment]
This has been fixed, will ship with the next version.
