### ISSUE TITLE
Formatting marks on new lines export as paragraph text

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#177]
### Steps to reproduce
p. or bc. on a new line exports into the reports as paragraph text

This is a problem because the tool import parser automatically adds a p. after a bc.. to break the code block (otherwise everything else in the field would be trapped in the code block). But, when there is no more content within the field, the trailing p. is currently exporting into the report as paragraph text.

Bug initially reported by Jarmo

**Comment by etdsoft** [comment]
Fixed, ships in the next release.
