### ISSUE TITLE
Sub-nodes disappear from the UI

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#179]
### Steps to reproduce
1. add a top node named example.com
2. add sub-nodes named f1 and f1_2010 to example.com
3. move f1_2010 node to f1, and all sub-nodes in example.com get disappeared

![replicate](https://user-images.githubusercontent.com/11186655/32123997-ef69645e-bb2b-11e7-8d96-94409449745a.gif)

### Note
the nodes are still in the DB (i.e. you can access them by ID).
it's a combination of a UI issue and a DB issue. The app is getting confused about what nodes have or don't have children and the UI gets messed up.

This seems to be a bug upstream that we're investigating:

amerine/acts_as_tree#63

**Comment by MattBudz** [comment]
resolved https://github.com/dradis/dradis-ce/pull/460
