### ISSUE TITLE
Links in code blocks formatted incorrectly

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#180]
### Steps to reproduce

If a link is inside a code block (e.g. `bc`), it will appear in the report in textile format.

Example format in Dradis:
```
#[Output]#
bc.. The following directories are browsable :

http://www.google.es/manual/style/xsl/
http://www.google.es/manual/style/css/
http://www.google.es/manual/style/
http://www.google.es/manual/images/
http://www.google.es/manual/style/lang/
http://www.google.es/manual/style/latex/
```

Exports into the report as:
evidence-2

### Expected behavior
Should export into the Word report like: 
```
The following directories are browsable :

http://www.google.es/manual/style/xsl/
http://www.google.es/manual/style/css/
http://www.google.es/manual/style/
http://www.google.es/manual/images/
http://www.google.es/manual/style/lang/
http://www.google.es/manual/style/latex/
```

### Actual behavior
Exports into the Word report like: 

![replicate](https://user-images.githubusercontent.com/11186655/32124209-97406754-bb2c-11e7-904f-503d04b85289.png)

Originally reported by Kulisu

**Comment by MattBudz** [comment]
This has been resolved
