### ISSUE TITLE
Dashes/Parentheses in link text break the formatting on export

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#182]
### Steps to reproduce
If the link text (format "Our website":http://drad.is) contains a dash `-` or parentheses `(` or `)`, the link formatting breaks on export.

Example Dradis content
```
"OWASP Top 10: A6 - Sensitive data exposure":https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure

"OWASP Top 10: A6 Sensitive data exposure":https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure
```

### Expected behavior
Should export like this: 

[OWASP Top 10: A6 - Sensitive data exposure](https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure)

[OWASP Top 10: A6 Sensitive data exposure](https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure)

### Actual behavior
Exports like so within Word:
![link](https://user-images.githubusercontent.com/11186655/32124538-bdc9d2d8-bb2d-11e7-82ed-825331839aa9.png)

### Workaround
Format the link text without dashes or parentheses.

Bug originally reported by Mark updated 03/08/18 to include the parentheses reported by Sasha.

**Comment by njfox** [comment]
Has there been any progress on this issue? Several common tool names contain dashes and it could be confusing for the reader to format the name with spaces instead.

**Comment by v-p-b** [comment]
I can also confirm this issue. Probably related to #207 .

**Comment by rachkor** [comment]
Fixed! This will ship in the next release.
