### ISSUE TITLE
Link with =< exports as ==<

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#183]
### Steps to reproduce
If a URL contains =<, it exports into a Word report as ==<

```
https://example.com/=<something>
https://example.com/<something>
```

### Expected behavior
Should export into the Word report like: 
```
https://example.com/=<something>
https://example.com/<something>
```

### Actual behavior
Exports into the Word report like: 

```
https://example.com/==<something>
https://example.com/<something>
```

Issue initially reported by Jarmo

**Comment by MattBudz** [comment]
This has been resolved
