### ISSUE TITLE
License renewal reminder shows HTML tags

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#185]
### Steps to reproduce
The **License is about to expire** link to renew your license does not display correctly in the header, showing HTML tags instead of a hyperlink:

![renew](https://user-images.githubusercontent.com/11186655/32124922-55895b2e-bb2f-11e7-8f3a-5e4236ee3549.png)

Workaround:
Navigate directly to `/pro/license/new` in the browser

Bug initially reported by Joseph

**Comment by MrJester** [comment]
I just found this issue today on my Dradis 2.9 deployment.

**Comment by sdupreez** [comment]
Found this same bug in our Dradis 3.0 installation

**Comment by stephenreda** [comment]
confirmed in 3.1.1

**Comment by etdsoft** [comment]
Fixed, ships in the next release.
