### ISSUE TITLE
Accessing Client Properties priority support

### ISSUE THREAD

**Issue by etdsoft** [dradis/dradis-ce#198]
> in Dradis, we put in several information about the clients in the web interface. However, in the report, we cannot reuse this data (to the best of my knowledge). It would be great to have some "variable" that you can use within Dradis to refer back to the properties of the clients.

Originally requested by Benne.

I think we can use the `ReportContentInitializer` to include any custom Client / Project fields already defined.

**Comment by MattBudz** [comment]
closed due to inactivity
