### ISSUE TITLE
Sorting of the Issue table

### ISSUE THREAD

**Issue by etdsoft** [dradis/dradis-ce#199]
> This is the ability to sort according a field in the issue table. For example, I would like to sort against the Title field - it would be cool to be able to click on the Field name to sort the table ascending/descending according to the clicked field.

Originally requested by Benne.

**Comment by mgargiullo** [comment]
Dan,

I have this on my wish list to add as well.  Being able to sort (and filter) the All Issues table on any displayed field would be a huge time saver during testing.

I was actually going to take a peek into the code over the holidays to see if I could contribute this bit.

Mike

**Comment by etdsoft** [comment]
@mgargiullo this is the file that contains the basics:

https://github.com/dradis/dradis-ce/blob/master/app/assets/javascripts/snowcrash/modules/items_table.js.coffee

I think that the initial version of this should let you sort by column, and don't persist sort. A later version can use localstorage to a) save the sort column and order; b) redraw and sort the table after rendering by the server.

**Comment by haseebeqx** [comment]
Hi Can I Take this one. I wish to contribute
