### ISSUE TITLE
cannot load such file -- coffee-script (LoadError)

### ISSUE THREAD

**Issue by qunxyz** [dradis/dradis-ce#2]
There's a bug when process installation.
in `require': cannot load such file -- coffee-script (LoadError)

for solution, please check this:
https://github.com/activeadmin/activeadmin/issues/1544

**Comment by etdsoft** [comment]
What installation instructions are you using package or git?

At what step in the process described bellow did you find the problem:

http://dradisframework.org/documentation/install_git.html

**Comment by etdsoft** [comment]
Closing for now, feel free to re-open with more details.
