### ISSUE TITLE
Word Table Rendering Issue

### ISSUE THREAD

**Issue by mgargiullo** [dradis/dradis-ce#200]
### Steps to reproduce

Add this table to a sample project:
```
#[TopTenRisk]#
|x.x.84.7|x.x.84.7|0.0|0|0|0|0.0%|
|x.x.84.6|x.x.84.6|0.0|0|0|0|0.0%|
|x.x.84.5|x.x.84.5|0.0|0|0|0|0.0%|
|x.x.175.18|provsso.example.com|0.0|0|0|0|0.0%|
|x.x.175.17|portal.example.com|0.0|0|0|0|0.0%|
|x.x.175.14|webmail.example.com|0.0|0|0|0|0.0%|
|x.x.175.11|pro.example.com|2.6|0|0|1|7.2%|
|x.x.175.13|vpn.example.com|9.8|0|0|2|27.0%|
|x.x.175.10|www.example.com|9.8|0|0|2|27.0%|
|x.x.175.15|asd.example.com|14.1|0|0|3|38.8%|
```

In reality, you only need this row to reproduce the issue:

`|x.x.175.10|www.example.com|9.8|0|0|2|27.0%|`

### Expected behavior
When Dradis generates the Word document, we'd expect a 7 column table to be created.

### Actual behavior
In the full table sample above, 9 of the 10 table rows are created with 7 columns.  The row that contains the www.domain.com record has 13 columns, breaking the table and macros that manipulate the table.

### System configuration
**Dradis version**:
2.8.1

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

**OS version**:
Linux dradispro 3.2.0-4-amd64 #1 SMP Debian 3.2.93-1 x86_64

**Comment by mgargiullo** [comment]
I believe this is a combination of the link auto parser and issue 180.  See: https://github.com/dradis/dradis-ce/issues/180

**Comment by MattBudz** [comment]
resolved
