### ISSUE TITLE
When I create multiple ContentBlocks, I want them to be displayed in alpha-order both in Dradis and in the report, so I can understand how things will end up in the report.

### ISSUE THREAD

**Issue by etdsoft** [dradis/dradis-ce#206]
### Steps to reproduce

1. Add a ContentBlock and give it a title of "Story 2"
2. Add a ContentBlock and give it a title of "Story 1"

### Expected behavior
The blocks are alpha-sorted both in the UI and the report.

### Actual behavior
The blocks are presented in creation order both in the UI and the report.

### System configuration
**Dradis version**: 2.9

**Comment by aapomm** [comment]
Fixed in:

- https://github.com/dradis/dradis-plugins/pull/14
