### ISSUE TITLE
Non-latin characters break hyperlinks in Word

### ISSUE THREAD

**Issue by etdsoft** [dradis/dradis-ce#207]
### Steps to reproduce

Create a basic template and project. Add an issue with the following content:

```
#[Title]#
Linky time!

#[Description]#

"HungarianNotHiperlinkWörd":http://ThisIsAHyperlink.org
```

### Expected behavior

The hyperlink should show up nicely both in Dradis and in Word.

### Actual behavior

The hyperlink shows up nicely in Dradis and not so nicely in Word:

<img width="384" alt="screen shot 2018-01-25 at 5 34 41 pm" src="https://user-images.githubusercontent.com/53006/35400073-21ba61f4-01f6-11e8-97bd-4813fbe91649.png">

### System configuration
**Dradis version**: 2.9

**Comment by v-p-b** [comment]
Do you have any updates on this?

**Comment by rachkor** [comment]
Fixed! This will ship in the next release.
