### ISSUE TITLE
Feature Suggestion: Access to previously generated reports

### ISSUE THREAD

**Issue by danielmncastro** [dradis/dradis-ce#214]
### Steps to reproduce
1) For any project, generate/Export a report in Word format.
2) Close browser
3) Open browser and access the project, there is no way of recovering previous reports.

### Expected behavior
After a report is generated, an user should be able to access the file at any later time, except if the file was removed (for space concerns). 
This is particularly important in the case of very long reports, where network errors can occur or the user may need to disconnect and return to work at a later time. There should be no need to restart the report generation from the beginning. 

### Actual behavior
If we request a report to be generated, the system creates a temporary link to download the file. If we lose connection or wait for too long, the report is lost and needs to be generated again. 

### System configuration
**Dradis version**:
Dradis Professional Edition v2.9.0 

**Ruby version**:
?

**OS version**:
?

**Comment by rachkor** [comment]
Hi @danielmncastro I think we actually have some built-in functionality that will accomplish the same thing for you. Recently-exported reports are available in the `/opt/dradispro/dradispro/current/tmp/` folder of your Pro instance. The files are named with the Project ID like dradis-word_report-ID.docm (e.g. dradis-word_report-123.docm). 

You can also export reports from the command line to avoid problems with the app timeout: https://dradisframework.com/pro/support/guides/debug_template/command_line_export.html. Or, you can increase in app timeout period too: https://dradisframework.com/pro/support/guides/customization/increase_session_timeout.html

**Comment by danielmncastro** [comment]
Thanks, @rachkor. One question/comment: I only have access to the Web interface, not to the underlying OS. I think this may be the case for other users as well.
