### ISSUE TITLE
burp-dradis: Cannot send issues generated by Retire.js to Dradis

### ISSUE THREAD

**Issue by njfox** [dradis/dradis-ce#227]
I'm not sure if this is an issue with [burp-dradis](https://github.com/dradis/burp-dradis) or with [burp-retire-js](https://github.com/h3xstream/burp-retire-js), but nothing happens when I right click a Retire.js issue and click "Send to Dradis" from the context menu. The "Issue Sent" window doesn't pop up and there is no output or errors in the Dradis extension. 

I'd be happy to try and submit a PR to fix it but I'm curious if anyone has any ideas on what could be causing this behavior.

**Comment by rachkor** [comment]
@njfox we haven't had any other reports of this error with burp-dradis so my hunch is that it's related to the Retire.js extension. Any PRs would be greatly appreciated!
