### ISSUE TITLE
Long node names are cut

### ISSUE THREAD

**Issue by aapomm** [dradis/dradis-ce#228]
### Steps to reproduce
Create a node with a very long label.

### Expected behavior
The node name breaks to a newline.

### Actual behavior
The node name does not break and gets cut.

![nodes](https://user-images.githubusercontent.com/1908272/38188248-b77a45f8-368d-11e8-8a15-f015bdc27383.png)

### System configuration
**Dradis version**: CE 3.9 / PRO 2.9

**Ruby version**: 2.4

**OS version**: Any

**Comment by MattBudz** [comment]
Fixed in v3.16
