### ISSUE TITLE
Content Block editor has problems in IE

### ISSUE THREAD

**Issue by rachkor** [dradis/dradis-ce#245]
### Steps to reproduce
Using Internet Explorer, navigate to Report Content page and edit a Content Block. 

The interface looks like this: 
![image001](https://user-images.githubusercontent.com/11186655/40194561-77a2331c-59d0-11e8-9385-1535751644a6.png)

### Expected behavior
The editor should be a reasonable width: 

<img width="945" alt="screen shot 2018-05-17 at 12 48 06 pm" src="https://user-images.githubusercontent.com/11186655/40194589-94815c88-59d0-11e8-8cf2-49a261af965e.png">

### System configuration
**Dradis version**: Pro v2.9.0

Issue originally reported by Alex

**Comment by MattBudz** [comment]
Tylium solved this:
![Uploading Screen Shot 2020-03-16 at 3.13.04 PM.png…](screencap from IE 11)
