### ISSUE TITLE
Feature Request: Admin Editable Dropdown Menu in top nav spaces

### ISSUE THREAD

**Issue by mgargiullo** [dradis/dradis-ce#247]
I would love to have a dropdown menu that the Admins could edit via the Settings page.  The menu would allow us to add direct links to either in app plugins (e.g. CVSS Calculator) or external with the option to open in the same or new window.

Like this: 
<img width="761" alt="afilias-au-dc-va_cis-201805_-_dradis_professional_edition" src="https://user-images.githubusercontent.com/13081537/40559414-b03bd840-6024-11e8-854f-9da53a5e5979.png">

**Comment by rachkor** [comment]
Thanks @mgargiullo! I've added this feature request to our idea backlog to investigate adding in the future.
