### ISSUE TITLE
Include Issue Title at the Evidence Level

### ISSUE THREAD

**Issue by catsec12** [dradis/dradis-ce#312]
### Steps to reproduce

When parsing Nessus, report evidence will only export corresponding evidence from the nessus file. For example, each host that is identified as having missing Microsoft patches will include specific version numbers: 

```
10.10.10.10 (IP)

 KB : 2928120
 - C:\Windows\system32\gppref.dll has not been patched.
   Remote version : 6.2.9200.16384
   Should be      : 6.2.9200.16859
```

### Expected behavior
It would be useful to make additional nessus fields available in the Evidence section, such as Issue titles. Instead of having exact version numbers, it would also be useful to include MS numbers as well (which is located in the Issue Title.
The expected output should look like this:

```
10.10.10.10   (IP)
MS14-025: Vulnerability in Group Policy Preferences Could Allow Elevation of Privilege

```
### System configuration
**Dradis version**:
2.9.0

**Comment by rachkor** [comment]
Apologies @catsec12, this should have been closed when we pushed the fix! This is now resolved and you can pull the Issue Title down to the Evidence level in Nessus.
