### ISSUE TITLE
Database migration broken

### ISSUE THREAD

**Issue by brianclemens** [dradis/dradis-ce#321]
### Steps to reproduce
On a fresh copy of dradis-ce pointed at a MariaDB instance, try creating the database

### Expected behavior
Running `bin/rails db:migrate RAILS_ENV=development` should create the database.

### Actual behavior
Running `bin/rails db:migrate RAILS_ENV=development` gets most of the way through creating the database before eventually reaching this error:
```
== 20161114111520 AddProjectIdToVersions: migrating ===========================
-- add_reference(:versions, :project, {:type=>:integer, :index=>true, :foreign_key=>true})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'dradis.projects' doesn't exist: SHOW FULL FIELDS FROM `projects`
```

### System configuration
**Dradis version**: cb33380

**Ruby version**: 2.4.1

**OS version**: ruby:2.4.1-slim docker base image

**Comment by brianclemens** [comment]
Database can be created successfully with `rails db:schema:load`.  However with most rails applications I've used, `db:migrate` alone has worked just fine.  So I wonder if this is still an error?

**Comment by etdsoft** [comment]
thanks @brianclemens can you check out #322 to see if it fixes it?

**Comment by brianclemens** [comment]
@etdsoft yes that fixes it, thanks!
