### ISSUE TITLE
"By" field in Revision history not populated from API call

### ISSUE THREAD

**Issue by sdupreez** [dradis/dradis-ce#376]
### Steps to reproduce

When creating or updating an issue via the API, the "By" field in the Revision history for an issue is not populated.

### Expected behavior
Revision history for an issue should keep track of what changes have been made to an issue and who made the changes.

### Actual behavior
The "By" field is left blank when an issue is created or updated via the API.

### System configuration
**Dradis version**: 2.9 / 3.0

**Comment by etdsoft** [comment]
Thanks @sdupreez definitely need to look into it.

**Comment by MattBudz** [comment]
resolved
