### ISSUE TITLE
Instructions for pre-reqs on Kali

### ISSUE THREAD

**Issue by jumson** [dradis/dradis-ce#403]
### Steps to reproduce
Attempt to build Dradis on this Kali VM: https://support.offensive-security.com/#!pwk-kali-vm.md
According to these instructions: https://dradisframework.com/ce/documentation/install_git.html
Using recommended pre-reqs: https://dradisframework.com/ce/documentation/install_kali.html

### Expected behavior
Dradis builds without issue.

### Actual behavior
The output was that "autoconf" is required

### System configuration
**Dradis version**: whatever is the main version in git today
**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [i386-linux-gnu]
**OS version**: Linux kali 4.17.0-kali1-686 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) i686 GNU/Linux

### Suggestion
Include the additional pre-req on the recommended pre-reqs site:
https://dradisframework.com/ce/documentation/install_kali.html

new pre-req: apt install autoconf

**Comment by rachkor** [comment]
Hi @jumson, I apologize, I don't fully understand what's going on here yet. Were you able to build/run without a problem using `root` in Kali? What do you mean by `did not build`? Screenshots or copy/pastes of error messages appreciated!

**Comment by jumson** [comment]
I edited that initial issue. Honestly, it would only require a simple update to the website, if anything. It has more to do with whichever version of Kali that someone had installed anyways.
