### ISSUE TITLE
Plugin request: Testssl.sh

### ISSUE THREAD

**Issue by alirezakv** [dradis/dradis-ce#407]
There is no integration for SSL scanning tools in Dradis. It will be great if you can add support for testssl.sh tool which is aiamed on SSL scanning. It's under active development and supports almost all issues regarding SSL/TLS and it would be great if we can use it in Dradis. I have zero-experience in Ruby development so i can't do that myself.
website: https://testssl.sh/

**Comment by rachkor** [comment]
Thanks @alirezakv! I'm adding this to our idea backlog to investigate adding in the future. I'm also closing this Issue, not because we're not considering adding this in the future, but because we're tracking feature requests on our internal backlog and keeping these GitHub issues for bugs.
