### ISSUE TITLE
"Edit" in a Checklist within Methodologies returns "NoMethodError"

### ISSUE THREAD

**Issue by stevewillson** [dradis/dradis-ce#409]
### Steps to reproduce

Install Dradis-CE from github following the steps outlined in the installation guide. Start Dradis, login to server and select "Methodology" > "Add new" > "New Checklist"

Click the green "Edit" button for the checklist.

### Expected behavior

I expect to be able to edit and modify a checklist.

### Actual behavior

I receive a page "NoMethodError"
NoMethodError in Methodologies#edit

### System configuration

**Dradis version**: Dradis CE 3.11.0

**Ruby version**: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]

**OS version**: Kali-rolling (most recent patches applied as of 12/11/18)

**Comment by jumson** [comment]
I get this same error everytime. I'm also using Kali rolling. I edited the checklist manually and that works, yet the editing button from within the framework continues to have that error. I'll get some screenshots in here later to help substantiate.

**Comment by etdsoft** [comment]
@stevewillson @jumson could you confirm the fix in this PR https://github.com/dradis/dradis-ce/pull/419
