### ISSUE TITLE
tables not rendering in HTML

### ISSUE THREAD

**Issue by jumson** [dradis/dradis-ce#413]
### Steps to reproduce
I create a table within my evidence, such as:

table{border:1px solid black}.
|\3=. *_IP: 10.11.1.217_* |
|\3. SMTP Banner: _220 hotline.localdomain ESMTP Postfix_ |
|\3. HELO response: _501 Syntax: HELO hostname_ |
|_. IP |_. User |_. Response |
| 10.11.1.217 | domain admins | _501 5.1.3 Bad recipient address syntax_ |
|\3=. *Total time to scan 10.11.1.217: 54 seconds * |

and it renders beautifully in the browser:

![image](https://user-images.githubusercontent.com/20364758/50544010-da7dec00-0b9c-11e9-8015-f54f3051d488.png)

However, when I export to HTML, it completely fails to make a table.
It is rendered as: 
![image](https://user-images.githubusercontent.com/20364758/50544013-fed9c880-0b9c-11e9-8004-9c59a044e2bd.png)

And examining the HTML shows no HTML was used to make it into a table:
![image](https://user-images.githubusercontent.com/20364758/50544021-1dd85a80-0b9d-11e9-9d4a-d18a27194b98.png)

Help us help you, how can we reproduce the problem?
The steps above should work with every HTML export template found here: https://dradisframework.com/academy/industry/compliance/

### Expected behavior
Some kind of table-like structure should appear, similar to how it normally renders.

### Actual behavior
see shots above

### System configuration
**Dradis version**:
I pulled this from https://github.com/dradis/dradis-ce.git on 23 December 2018.

**Ruby version**:
ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]

**OS version**:
/etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.1"
VERSION_ID="2019.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by jumson** [comment]
I just noticed pull request #17, in https://github.com/dradis/dradis-html_export/pull/17
@dormi , I think that would address this issue?

**Comment by rachkor** [comment]
@jumson you're correct! Keep an eye on that PR for updates and we should have this resolved for you.

**Comment by jumson** [comment]
Actually, I edited the `Gemfile.plugins.template` file to get that new html plugin branch -- it seems to work beautifully.

It does not have the pretty formatting, but at least it is a table-like structure:
![image](https://user-images.githubusercontent.com/20364758/50726073-ad5d9c00-10bc-11e9-837d-c641fb445203.png)

The above comes from the same code that generated this in the regular dradis view:
![image](https://user-images.githubusercontent.com/20364758/50726089-f9104580-10bc-11e9-98d7-f531c01021e8.png)

And both of those come from this code:
```
table{border:1px solid black}.
|\3=. *_IP: 10.11.1.22_* |
|\3. SMTP Banner: _220 barry ESMTP Sendmail 8.11.6/8.11.6; Sat, 29 Dec 2018 18:47:39 +0200_ |
|\3. HELO response: _501 5.0.0 HELO requires domain address_ |
|_. IP |_. User |_. Response |
| 10.11.1.22 | root | _250 2.1.5 root <root@barry>_ |
| 10.11.1.22 | bin | _250 2.1.5 <bin@barry>_ |
| 10.11.1.22 | daemon | _250 2.1.5 <daemon@barry>_ |
| 10.11.1.22 | games | _250 2.1.5 <games@barry>_ |
| 10.11.1.22 | nobody | _250 2.1.5 <nobody@barry>_ |
|\3=. *Total time to scan 10.11.1.22: 139 seconds * |
```

If I want to outline each cell or row, it takes more code...I found [this source](https://www.question-defense.com/2009/05/22/outline-every-cell-in-every-row-of-a-table-using-textile-formatting) explaining it.

So I can get HTML export output like this:
![image](https://user-images.githubusercontent.com/20364758/50726159-df233280-10bd-11e9-9de4-af280569c1fd.png)

using code like this:
```
table{border:1px solid black}.
|\3={border:1px solid black}. *_IP: 10.11.1.22_* |
|\3{border:1px solid black}.. SMTP Banner: _220 barry ESMTP Sendmail 8.11.6/8.11.6; Sat, 29 Dec 2018 18:47:39 +0200_ |
|\3{border:1px solid black}.. HELO response: _501 5.0.0 HELO requires domain address_ |
|_{border:1px solid black}.. IP |_{border:1px solid black}.. User |_{border:1px solid black}.. Response |
|{border:1px solid black}. 10.11.1.22 |{border:1px solid black}. root |{border:1px solid black}. _250 2.1.5 root <root@barry>_ |
|{border:1px solid black}. 10.11.1.22 |{border:1px solid black}. bin |{border:1px solid black}. _250 2.1.5 <bin@barry>_ |
|{border:1px solid black}. 10.11.1.22 |{border:1px solid black}. daemon |{border:1px solid black}. _250 2.1.5 <daemon@barry>_ |
|{border:1px solid black}. 10.11.1.22 |{border:1px solid black}. games |{border:1px solid black}. _250 2.1.5 <games@barry>_ |
|{border:1px solid black}. 10.11.1.22 |{border:1px solid black}. nobody |{border:1px solid black}. _250 2.1.5 <nobody@barry>_ |
|\3={border:1px solid black}.. *Total time to scan 10.11.1.22: 139 seconds * |
```

**Comment by jumson** [comment]
Actually, just found another workaround for all that ugly code, including a CSS class. 
I edited the `default_dradis_template_v3.0.html.erb` file and added `#tableborders td {border:2px solid black;}`, which I got from [that source](https://www.question-defense.com/2009/05/22/outline-every-cell-in-every-row-of-a-table-using-textile-formatting) above. 

Now, this code:
```
table(#tableborders){border:2px solid black;font-family: georgia}.
|\3=. *_IP: 10.11.1.22_* |
|\3. SMTP Banner: _220 barry ESMTP Sendmail 8.11.6/8.11.6; Sat, 29 Dec 2018 18:47:39 +0200_ |
|\3. HELO response: _501 5.0.0 HELO requires domain address_ |
|_. IP |_. User |_. Response |
| 10.11.1.22 | root | _250 2.1.5 root <root@barry>_ |
| 10.11.1.22 | bin | _250 2.1.5 <bin@barry>_ |
| 10.11.1.22 | daemon | _250 2.1.5 <daemon@barry>_ |
| 10.11.1.22 | games | _250 2.1.5 <games@barry>_ |
| 10.11.1.22 | nobody | _250 2.1.5 <nobody@barry>_ |
|\3=. *Total time to scan 10.11.1.22: 139 seconds * |
```

When exported to HTML, appears like this:
![image](https://user-images.githubusercontent.com/20364758/50726353-b8b2c680-10c0-11e9-8b9f-8ecc3ac16729.png)

**Comment by alexsalvetti** [comment]
Hi @jumson , I would like to know what you have modified on the gemfile to get the table rendering working again.
> Actually, I edited the `Gemfile.plugins.template` file to get that new html plugin branch -- it seems to work beautifully.
Thanks in advance

**Comment by alexsalvetti** [comment]
Ok thanks @dormi but the string you wrote has a problem with the  \` \` instead of ' ' in the branch.

so the command that works for me is this:
`gem 'dradis-html_export', '~> 3.11', github: 'dradis/dradis-html_export', branch:  'render-using-rails'`

**Comment by MattBudz** [comment]
resolved
