### ISSUE TITLE
Import of NMAP XML duplicates data

### ISSUE THREAD

**Issue by benmeyer50** [dradis/dradis-ce#43]
When I imported the data from  an initial nmap and then ran nmap again to collect more data and imported that new file the data was duplicated instead of just updated with the additional details. This shows in the notes and services area within the details of a node.

**Comment by etdsoft** [comment]
Hi @benmeyer50 that shouldn't have been the case, but I can reproduce. Please watch this space.

**Comment by hktalent** [comment]
import metasploit  、nmap ...xml is nothing , no data display

**Comment by rachkor** [comment]
@hktalent that sounds like an unrelated issue. Is your background worker running? See this thread for more details: http://discuss.dradisframework.org/t/issues-with-uploads/328/2?u=rachkor
If that's not the cause of your upload problem, please open a new issue tracker entry here and we'll help troubleshoot: https://github.com/dradis/dradis-ce/issues/new
