### ISSUE TITLE
PTES methodologies undefined

### ISSUE THREAD

**Issue by musiyenko** [dradis/dradis-ce#442]
### Steps to reproduce

Follow the instructions on PTES installation

### Expected behavior
Open methodologies tab and find everything in place

### Actual behavior
PTES methodologies are undefined

### System configuration
**Dradis version**:
Latest master

**Ruby version**:
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]

**OS version**:
Kernel: 4.20.10-arch1-1-ARCH

**Comment by rachkor** [comment]
@musiyenko Thank you for reporting this! We're working on a fix now and will let you know as soon as it's available.

**Comment by dormi** [comment]
This is an updated file: 
[dradis_ce_compliance_package-PTESv0.4.1.zip](https://github.com/dradis/dradis-ce/files/2918843/dradis_ce_compliance_package-PTESv0.4.1.zip)

**Comment by musiyenko** [comment]
Looks good to me! Thank you for a quick fix and an email you've sent me :+1:
