### ISSUE TITLE
Installing process on ubuntu 18.10 fails

### ISSUE THREAD

**Issue by Meru3m** [dradis/dradis-ce#449]
### Steps to reproduce
I installed a fresh Ubuntu installation, update+upgrade, installed GIT and RUBY and tried to install with:

$ git clone https://github.com/dradis/dradis-ce.git
$ cd dradis-ce/
$ sudo ./bin/setup [or sudo ruby bin/setup]

### Expected behavior
I expected to conclude the installation

### Actual behavior
I got the following error:
<img width="1206" alt="Screenshot 2019-04-03 at 20 35 51" src="https://user-images.githubusercontent.com/13599910/55504198-a1985c00-5650-11e9-8844-062d892cb8a5.png">

### System configuration
**Dradis version**: last (date 3 April 2019)

**Ruby version**: 2.5.1p57

**OS version**: Ubuntu 18.10

**Comment by rachkor** [comment]
@Meru3m thanks for reaching out! Based on the error message, it looks like we need to get the `bundler` gem installed before the `bundle install` command will work as expected. Can you try the following? 
```
$ gem install bundler
$ ./bin/setup
```
Let me know how it goes!

**Comment by etdsoft** [comment]
Lines 3 and 4 of the output seem to indicate that `bundler` was indeed installed.

@Meru3m can you try again but without using `sudo`?

**Comment by Meru3m** [comment]
Hi @etdsoft,

I ran it with sudo, here is the complete output:
<img width="904" alt="Screenshot 2019-04-04 at 09 31 06" src="https://user-images.githubusercontent.com/13599910/55537416-6f244880-56bc-11e9-88fc-1b5f7fad173f.png">

Same result for ./bin/setup

It could be some missing packages? It is a fresh ubuntu installation.
Thank you

**Comment by d0nu75** [comment]
@Meru3m try:
`gem install bundler --version '1.16.1'`

**Comment by rachkor** [comment]
@Meru3m what is the output of the following? 
`$ bundler -v`
I'm suspicious that bundler v2 is causing problems. We may need to specifically install a bundler v1 to make this work!

**Comment by Meru3m** [comment]
Hello @rachkor 

here's the output:
![image](https://user-images.githubusercontent.com/13599910/55868261-67651800-5b84-11e9-9c14-005edfee575c.png)

Should I install it with: 
`gem install bundler -v 1.0.10`

Thank you

**Comment by dormi** [comment]
@Meru3m if you pull the most recent changes, bundler `2.0.1` should be good.
`sudo` should not be necessary.

**Comment by HuanTianyu** [comment]
Hello！I also encountered the same problem, but it has been solved. My dradis-ce has been installed and used under my Dr. Here are the steps to solve it.

1. Use `sudo -i` switch to root user
2. Install rvm
`bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)` 
3. Install ruby 2.4.1
`rvm install ruby-2.4.1` 
4. Switch to dradis-ce directory
5. Use `ruby -v` check whether the ruby version is 2.4.1
6. Next you need to use the following two instructions to install mysql2
`apt-get install build-essential libmysqlclient-dev`
`gem install mysql2 -v '0.5.2'`
7. After the installation of mysql2 is completed, you can proceed with the installation of dradis-ce.
 `ruby /bin/setup`

**Comment by HuanTianyu** [comment]
Hello！I also encountered the same problem, but it has been solved. My dradis-ce has been installed and used under my Dr. Here are the steps to solve it.

1. Use `sudo -i` switch to root user
2. Install rvm
`bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)` 
3. Install ruby 2.4.1
`rvm install ruby-2.4.1` 
4. Switch to dradis-ce directory
5. Use `ruby -v` check whether the ruby version is 2.4.1
6. Next you need to use the following two instructions to install mysql2
`apt-get install build-essential libmysqlclient-dev`
`gem install mysql2 -v '0.5.2'`
7. After the installation of mysql2 is completed, you can proceed with the installation of dradis-ce.
 `ruby /bin/setup`

**Comment by dormi** [comment]
Thank you @HuanTianyu !

1 comments: 

- You should be able to skip `gem install mysql2 -v '0.5.2'` as it ins included in the `Gemfile.lock` (https://github.com/dradis/dradis-ce/blob/master/Gemfile.lock#L199) and should be installed by bundler in `bin/setup`.

**Comment by MattBudz** [comment]
closed due to inactivity
