### ISSUE TITLE
Setup Dradis-Ce in Ubuntu 18.04

### ISSUE THREAD

**Issue by g4laad** [dradis/dradis-ce#450]
### Steps to reproduce

Fresh install of Ubuntu 18.04. Installation of rbenv and ruby 2.4.1 required by Dradis.
$ git clone https://github.com/dradis/dradis-ce.git
$ cd dradis-ce/
$ ./bin/setup (non-root user)
### Expected behavior
Complete the installation

### Actual behavior
I have the following error:
![image](https://user-images.githubusercontent.com/11516870/55734133-4e8f2200-5a1f-11e9-9a9f-52c69c475e6c.png)

### System configuration
**Dradis version**: last from git (8 April 2019)

**Ruby version**: 2.4.1

**OS version**: 18.04.2

**Comment by etdsoft** [comment]
paging @dormi

**Comment by dormi** [comment]
@g4laad I can reproduce it too.
Fixed in https://github.com/dradis/dradis-ce/pull/451
If you pull the latest changes it should be fixed.

**Comment by g4laad** [comment]
Yes it's works well now, thank you !
