### ISSUE TITLE
Quick-Edit in Search

### ISSUE THREAD

**Issue by mgl-tuev** [dradis/dradis-ce#457]
It would be nice, to have an edit button within the search function to edit a found item directly.

![dradis_search](https://user-images.githubusercontent.com/50363592/57295220-539ccb00-70ca-11e9-85ee-a1ca031d3727.png)

**Comment by rachkor** [comment]
Thank you @mgl-tuev! I've added this to our internal idea backlog where feature requests are tracked so that we can investigate adding this in the future.
