### ISSUE TITLE
Dradis::Plugins::Netsparker lacks Issue Preview

### ISSUE THREAD

**Issue by mavensecurity** [dradis/dradis-ce#459]
### Steps to reproduce
Applied changes from latest clone of https://github.com/dradis/dradis-netsparker as of today/now. (Including `god restart`)

Go to https://dradisproVM/pro/admin/plugins/Dradis::Plugins::Netsparker/edit

Look at Preview area. 
 
### Expected behavior
A template showing sample Issue.

### Actual behavior
Sorry, the Plugin Manager can only render
previews of XML-based templates and
Dradis::Plugins::Netsparker is not using one.

### System configuration
**Dradis version**:
Dradis Professional Edition v3.2.0

**Ruby version**:

**OS version**:

**Comment by etdsoft** [comment]
Confirmed, bug! And fixed:

https://github.com/dradis/dradis-netsparker/commit/2a1a0805ea20212d90a2839e58f1fd9a0368bba0

You may need to edit the `/opt/dradispro/dradispro/shared/templates/plugins/netsparker/issue.sample` in your VM to fix the broken tag.
