### ISSUE TITLE
[Feature request] Ship Mitre CWE as default vulnerability templates

### ISSUE THREAD

**Issue by noraj** [dradis/dradis-ce#470]
## Feature Request

It is nice that Dradis can import vulnerability templates but it would be even better if it was packaged with one provided.

### Example Use Case

For example Faraday comes with the MITRE CWE in a data dir (https://github.com/infobyte/faraday/tree/master/data), so a small team or bounty hunters that need generic vulnerabilities could import the data very easily and works with this.

**Comment by rachkor** [comment]
@noraj, thanks for this! Are you requesting this for Dradis CE or Pro? Pro ships with the IssueLibrary that includes our seed data: https://dradisframework.com/support/guides/issuelibrary/

**Comment by noraj** [comment]
@rachkor For the CE version.

**Comment by rachkor** [comment]
Hi @noraj, thanks for confirming! This is a pro-only feature at this time but we appreciate the feedback.
