### ISSUE TITLE
Can't establish a connection to the server at 127.0.0.1:3000

### ISSUE THREAD

**Issue by sh1va73** [dradis/dradis-ce#521]
Dradis starts up and gives an 'exit error' code. Because of this it cant establish a connection in the webbrowser. Any ideas how i can get it running?

**Comment by rachkor** [comment]
@sh1va73 how did you install Dradis? Can you give this guide a try? https://dradisframework.com/ce/documentation/install_git.html

**Comment by sh1va73** [comment]
I used the default installation on the latest Kali version. Should I delete that version and then install again from GitHub?

**Comment by rachkor** [comment]
In that case, I would recommend using these slightly modified instructions: https://dradisframework.com/ce/documentation/install_kali.html. They're still GitHub-based so yes, but you'll get all the Kali dependencies there.
