### ISSUE TITLE
Include the author as well of the plugin in Issues created via tool upload

### ISSUE THREAD

**Issue by etdsoft** [dradis/dradis-ce#58]
When I upload the output of a security scanner, I want my name to appear next to the tool name in the :author field of the Issue, so others in the project know who uploaded what tool output.

This behaviour is controlled by dradis/dradis-plugins.

The request was originally mentioned by Bill.

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future
