### ISSUE TITLE
Cancel link on Note Edit page always redirects to Node 

### ISSUE THREAD

**Issue by lifecoderua** [dradis/dradis-ce#585]
### Steps to reproduce

- Create a new Note;
- Edit the Note;
- Click "Cancel" link;

### Expected behavior
Redirect to the **Note** page;

### Actual behavior
Redirect to the **Node** Properties page;
(this is expected for a new Note, but not for an existing one)

### System configuration
**Dradis version**:
Dradis Community v3.15.0

**Ruby version**:
2.4.1

**OS version**:
macOS 10.15.2

**Comment by brianp** [comment]
Closed by @lifecoderua contribution at #586 

I'll note it's still strange to cancel a new note and appear on the node summary page. I think it would make more sense to appear on the Note tab for the node. But this is a bigger deep linking problem we have, which is being looked at elsewhere. So this fix is much appreciated and a better starting place for now.
