### ISSUE TITLE
Validator fails to find missing images

### ISSUE THREAD

**Issue by mgargiullo** [dradis/dradis-ce#595]
### Steps to reproduce

1. Create a project.
2. Add an Issue.
3. Add Evidence to Issue
4. Add a bogus image to an exported field.
5. Generate Word Report

For example, if your word report expects an evidence field named `#[proof]#`, add the following image to the field.

`!/pro/projects/10316/nodes/301131/attachments/notarealfile.png!`

### Expected behavior
The export validator should list the missing image as an error.

### Actual behavior
It doesn't mention the missing image, but fails to generate the WordDoc.

![error](https://user-images.githubusercontent.com/13081537/74777162-ea580400-5266-11ea-8510-4756a9c371ec.png)

Shows error in log:
`bundler: failed to load command: thor (/opt/dradispro/dradispro/releases/202002091800/vendor/bundle/ruby/2.4.0/bin/thor)
Errno::ENOENT: No such file or directory @ dir_initialize - /opt/dradispro/dradispro/releases/202002091800/attachments/301131`

### System configuration
**Dradis version**:
3.5.0

**Ruby version**:
2.4.0

**OS version**:
Debian 9

**Comment by etdsoft** [comment]
Hi @mgargiullo nice find.

Technically the screenshot validator is focussing on the syntax, so it's not "broken" in that sense, but could definitely be improved to handle this case.

**Comment by MattBudz** [comment]
This enhancement has been implemented.
