### ISSUE TITLE
Dradis requires unique project names

### ISSUE THREAD

**Issue by tgrimee** [dradis/dradis-ce#633]
### Steps to reproduce

Create a project with a name such as TEST. Create another project with the same name TEST.

### Expected behavior
Creating two different projects with the same name shouldn't be forbidden. Instead, projects should be identified with a unique random identifier.

### Actual behavior
Dradis will return an error stating projects require unique names, as shown in the attached image.

### System configuration
**Dradis version**: Dradis Professional Edition v3.4.1
![error - Copy](https://user-images.githubusercontent.com/7591423/78153247-24f2b600-743b-11ea-8060-96bcf7d55bc8.png)

**Comment by rachkor** [comment]
Hey @tgrimee, can you upgrade to the latest version of Dradis Pro, v3.6.1? This should resolve the error you're seeing and instead, if you try to create a project with a duplicate name, you'll see a nice "Name has already been taken" warning in the app (no stack trace!). As far as your feature request, I've already added that to our idea backlog to investigate adding in the future. I'm closing this tracker entry as we want to keep this list for just the CE bugs.
