### ISSUE TITLE
Attempting to rename a project produces an error

### ISSUE THREAD

**Issue by kriggins** [dradis/dradis-ce#634]
### Steps to reproduce
1. Click on edit on a project.
2. Change name to the name of a project that already exists.
3. Click save.

### Expected behavior
SHould get an error that the project name already exists.

### Actual behavior

Oops! Something went wrong. But don't fret!

Here's the error message:
[ActionView::Template::Error] undefined method `any?' for nil:NilClass

Here's the error stack:

/opt/dradispro/dradispro/releases/202002280818/app/views/projects/_form.html.erb:41:in `block in _app_views_projects__form_html_erb__3041632571503520785_47399118923460' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.4.1/lib/action_view/helpers/capture_helper.rb:41:in `block in capture' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.4.1/lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.4.1/lib/action_view/helpers/capture_helper.rb:41:in `capture' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.4.1/lib/action_view/helpers/form_helper.rb:452:in `form_for' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/simple_form-5.0.2/lib/simple_form/action_view_extensions/form_helper.rb:27:in `block in simple_form_for' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/simple_form-5.0.2/lib/simple_form/action_view_extensions/form_helper.rb:46:in `with_simple_form_field_error_proc' /opt/dradispro/dradispro/current/vendor/bundle/ruby/2.4.0/gems/simple_form-5.0.2/lib/simple_form/action_view_extensions/form_helper.rb:26:in `simple_form_for' /opt/dradispro/dradispro/releases/202002280818/app/views/projects/_form.html.erb:1:in `_app_views_projects__form_html_erb__3041632571503520785_47399118923460' /opt/dradispro/dradispro/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.1/lib/action_view/template.rb:159:in `block in render'

For more information, the application log can be found at /opt/dradispro/dradispro/releases/202002280818/log/production.log.

And finally, don't hesitate to mail our team and we'll be happy to help.

### System configuration
**Dradis version**:
3.6.0

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**OS version**:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by etdsoft** [comment]
thanks @kriggins I can confirm it’s bug.

When there's a validation error in the Project#form, the server fails to initialise a variable that the view needs.

**Comment by brianp** [comment]
A fix for this issue has been merged and will be available in the next release.

Thanks for reporting @kriggins !
