### ISSUE TITLE
Problem importing Issues from MediaWiki

### ISSUE THREAD

**Issue by jwdewidt** [dradis/dradis-ce#645]
When I Search an issue by mediawiki I Get the following Error

        @filter.run(@params)
      elsif @filter.respond_to?(:query)
        @filter.query(@params)
      end
    else
      [{

When I search via the api the results are found with:
http://127.0.0.1:8888/api.php?action=opensearch&search=SSL&format=json

### System configuration
**Dradis version**:
v3.16.0 Dradis-CE
**Ruby version**:
5.4.4
**MediaWiki version**:
1.34.1

**Comment by rachkor** [comment]
@jwdewidt this looks like a configuration issue. Did you follow these instructions to get Dradis connected to your MediaWiki? https://dradisframework.com/support/guides/customization/connect_mediawiki.html

**Comment by jwdewidt** [comment]
Off course, the ip address and port mentioned is the above api call are also used in the configuration settings in Dradis.

**Comment by jwdewidt** [comment]
Sorry, but I found it. An issue in my Docker environment.
