### ISSUE TITLE
Ruby version error when installing from git

### ISSUE THREAD

**Issue by kmahyyg** [dradis/dradis-ce#654]
### Steps to reproduce

When installing dradis-ce on both ArchLinux and Debian 10 from git, all failed due to gemfile defined an old ruby version, the system ruby version is 2.7.0, but gemfile require 2.4.1

### Expected behavior

Install finished as expected.

### Actual behavior

```
root@335fee06901b:~/dradis-ce# ./bin/setup

== Enabling default add-ons ==
== Installing dependencies ==
Your Ruby version is 2.7.0, but your Gemfile specified 2.4.1
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root
will break this application for all non-root users on this machine.
Your Ruby version is 2.7.0, but your Gemfile specified 2.4.1

== Command ["bundle install"] failed ==
```

### System configuration
**Dradis version**: Latest from Git

**Ruby version**: 2.7.0

**OS version**: Debian 10

### Related Issue

https://github.com/BlackArch/blackarch/issues/2655

**Comment by rachkor** [comment]
Hey @kmahyyg, check out this forum thread and let me know if you have any questions! https://discuss.dradisframework.org/t/installation-issue/740/5

**Comment by kmahyyg** [comment]
I just wanna pack it into a docker image, I checked the forum link you given above. You mean I need to install `rbenv` and only use `2.4.1` instead of patch `Gemfile` to  `2.7.0` ?

**Comment by kmahyyg** [comment]
Further Issue:

```
root@335fee06901b:~# rbenv install 2.4.1
Downloading ruby-2.4.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
Installing ruby-2.4.1...

WARNING: ruby-2.4.1 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.
```

You might need to update it since it's security-related.

**Comment by kmahyyg** [comment]
Upstream response doesn't solve my problem. Solved by using RVM in docker container. 

Issue Closed.
