### ISSUE TITLE
Install from git release failed

### ISSUE THREAD

**Issue by laim-user** [dradis/dradis-ce#731]
### Steps to reproduce

During the installation of there was a problem installing an additional plugin "dradis-openvas". The plugin version specified in the dependencies does not match.  As result, installation fails.

`$ ruby bin/setup`

![dradis-ce-failed](https://user-images.githubusercontent.com/18748117/89117205-71302e80-d4df-11ea-9ef4-457b2febff39.png)

### Expected behavior
Install project without problem

### Actual behavior
Can't finish install.

### System configuration
**Dradis version**: git 3.18 commit [(a44ace0)](https://github.com/dradis/dradis-ce/commit/a44ace0ff568e547fcebe76c063c89a2228dc2d4)

**Dradis openvas version**: git 3.18.0.rc1 commit [(6b7ebc6)](https://github.com/dradis/dradis-openvas/commit/6b7ebc6928adb53e3b462b49b01885694d4a0ec5)

**Ruby version**: ruby 2.4.1p111

**OS version**: Manjaro 20.0.3

**Comment by pritchyspritch** [comment]
I had this same issue and made a quick-fix by editing the `Gemfile.plugins` file, you can see the config in the [template](https://github.com/dradis/dradis-ce/blob/master/Gemfile.plugins.template#L33).

Changed the `~> 3.18` to `~> 3.18.0.rc1` and it worked.

**Comment by laim-user** [comment]
> Changed the `~> 3.18` to `~> 3.18.0.rc1` on the openvas line and it worked.

Hello! Thank you for the answer. I did just that. But the problem didn't go away in the repository:)

**Comment by aapomm** [comment]
Hi @laim-user. Apologies as this is a mistake on our part. The `dradis-openvas` v3.18.0 was tagged with the version 3.18.0.rc1, so bundler throws that error. I've updated that repo now and `~> 3.18` in the `Gemfile.plugins` file should work.

**Comment by laim-user** [comment]
Fixed. Thank you!
