### ISSUE TITLE
i am using dradis-plugin in my application , getting below error . i am facing this issue when i start sidekiq 

### ISSUE THREAD

**Issue by KMadhuSudhan** [dradis/dradis-ce#74]
uninitialized constant ProjectScopedController
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `const_get'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `each'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `inject'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `constantize'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/konda.madhusudhan/RailsSpace/jackhammer/web/dradis-plugins/app/controllers/dradis/plugins/export/base_controller.rb:4:in `<module:Export>'
/Users/konda.madhusudhan/RailsSpace/jackhammer/web/dradis-plugins/app/controllers/dradis/plugins/export/base_controller.rb:3:in `<module:Plugins>'
/Users/konda.madhusudhan/RailsSpace/jackhammer/web/dradis-plugins/app/controllers/dradis/plugins/export/base_controller.rb:2:in `<module:Dradis>'
/Users/konda.madhusudhan/RailsSpace/jackhammer/web/dradis-plugins/app/controllers/dradis/plugins/export/base_controller.rb:1:in `<top (required)>'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:471:in `each'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:471:in `block in eager_load!'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:469:in `each'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:469:in `eager_load!'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:346:in `eager_load!'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `each'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/Users/konda.madhusudhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/Users/konda.madhusudhan/RailsSpace/jackhammer/web/app/config/environment.rb:5:in `<top (required)>'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:233:in `boot_system'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:49:in `run'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.1/bin/sidekiq:12:in `<top (required)>'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/bin/sidekiq:23:in `load'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/bin/sidekiq:23:in `<main>'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by etdsoft** [comment]
Hi @KMadhuSudhan,

When you say:

> using dradis-plugin in my application

That do you mean? `dradis-plugin` is meant to be used by `dradis-ce` and the Dradis Framework plugins not by external applications. What is the use case?

HTH

**Comment by KMadhuSudhan** [comment]
Hi ,


dradis-plugin using by  external application not by dradis-ce

**Comment by etdsoft** [comment]
Closing as an actual bug report. Feel free to repost in the forum http://discuss.dradisframework.org
