### ISSUE TITLE
Link Team Name in Projects view to Team

### ISSUE THREAD

**Issue by mgargiullo** [dradis/dradis-ce#751]
### Steps to reproduce
Browse to /pro/projects
Click on Team Name (boxed in green in screenshot) should bring you to Team page

![Projects](https://user-images.githubusercontent.com/13081537/98578388-49ddc000-228b-11eb-865f-f01c68aeca76.png)

Team Page /pro/teams/<team_id>

![Team](https://user-images.githubusercontent.com/13081537/98578617-92957900-228b-11eb-9026-9a5fe08c13f2.png)

### Expected behavior
Ideally, clicking the Team name would bring you to the Team Page /pro/teams/<team_id>

### Actual behavior
Not yet implemented

### System configuration
**Dradis version**: 
v3.9.0

**Ruby version**: 
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**OS version**: 
Debian GNU/Linux 9
Linux dradispro 4.9.0-14-amd64 #1 SMP Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux

**Comment by rachkor** [comment]
Hey @mgargiullo thank you for this! I'm going to close this here as we've been moving away from GitHub issues and to our own internal backlog for feature requests. But, this has been heard and noted!
