### ISSUE TITLE
Unable to export to HTML

### ISSUE THREAD

**Issue by lukfe85** [dradis/dradis-ce#817]
Hi Dradis, 

I have just installed Dradis on Kali Linux OS and I am not able to export to HTML format. I am using the community version. 
I have tried to create the tmp folder, change permissions, nothing, The error I get is this one.

Version is 3.21.0
Kali Linux is: Linux kali 5.10.0-kali5-amd64 #1 SMP Debian 5.10.24-1kali1 (2021-03-23) x86_64 GNU/Linux
To install dradis, I used this link:
https://dradisframework.com/ce/documentation/install_kali.html
![screenshot](https://user-images.githubusercontent.com/80815574/113125967-76cd4800-9217-11eb-97da-0500d00a6e57.png)
Could someone help with the issue?
Thanks

**Comment by rachkor** [comment]
Hey @lukfe85, I should be able to help with this! What HTML report template are you exporting into?

**Comment by lukfe85** [comment]
Hi rachkor, 
Thanks for your message. I tried the 2 built-in plug-in (installed by default).

**Comment by sean-yeoh** [comment]
Hi @lukfe85 , can you check if this folder `dradis-ce/app/views/tmp` exists?

**Comment by MattBudz** [comment]
Closing, this issue has been stale for 1+ year
