### ISSUE TITLE
'Contributors Agreement' in CONTRIBUTING.md is a dead link

### ISSUE THREAD

**Issue by jasonek** [dradis/dradis-ce#86]
I was reading CONTRIBUTING.md under the 'Submitting Changes' section. I tried to read the 'Contributors Agreement', but it redirects to the main repo of [dradis-legacy](https://github.com/dradis/dradis-legacy). Browsing through [dradis-ce](https://github.com/dradis/dradis-ce) and [dradis-legacy](https://github.com/dradis/dradis-legacy), I can't find a 'Contributors Agreement'.

However I did find a [cache of the old agreement](https://webcache.googleusercontent.com/search?q=cache:u4UNJe20xcIJ:https://github.com/dradis/dradis-legacy/wiki/Contributor%27s-agreement+&cd=1&hl=en&ct=clnk&gl=us)

Is there a more updated one that I am missing? Does the dradis team want the reference to the agreement removed, to copy and use the old one, or to write a new agreement?

**Comment by etdsoft** [comment]
@jasonek many thanks for this. The page was there in the old repo's wiki, but the wiki module was hidden.

I've moved all of the relevant old pages to this repo's wiki and updated CONTRIBUTING.md.
