### ISSUE TITLE
Bug: inconsistent use of "Archived" status/state between Issue Library and Rules Engine

### ISSUE THREAD

**Issue by mavensecurity** [dradis/dradis-ce#896]
### Steps to reproduce

Marking an entry in Rules Engine with a Status of "Archived" will prevent it from being applied - which is expected.
Marking an entry in the Issue Library with a State of "Archived" does not prevent it from being applied by Rules Engine's "Match All - Find match in Library".

### Expected behavior
Having a quick way to archive Issue Library entries (withing editing each #[<tool>_id]# entry) would be useful, and seems to be the best interpretation of having an Issue with a State marked "Archived".

### Actual behavior
"Archived" Issue Library entry are still applied by the Rules Engine's "Match All - Find match in Library".

### System configuration
**Dradis version**: 3.12.2

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**OS version**: Debian 4.9.110

**Comment by rachkor** [comment]
Thank you @mavensecurity! I'm going to go ahead and close this as this is a Pro feature and we track those in an internal idea backlog. I've already added it there! The feedback is definitely appreciated.
