### ISSUE TITLE
Ubuntu 16.04 - Error parsing Gemfile

### ISSUE THREAD

**Issue by bobdob42** [dradis/dradis-ce#91]
>ruby bin/setup
>.
>[!] There was an error parsing `Gemfile`: Illformed requirement ["¬> 3.0"]. Bundler cannot continue.

Looks like there is a special character in the Gemfile.plugins.template file
gem 'dradis-qualys',      '¬> 3.0'

**Comment by etdsoft** [comment]
Can you please replace it with `'~> 3.0'`?

@th3xer0  is sending us a PR shortly. Sorry for the hassle!

**Comment by bobdob42** [comment]
yes, guessed it should of been, '~> 3.0', once replaced it all works fine.

**Comment by etdsoft** [comment]
This was fixed by #94
