### ISSUE TITLE
problems wih the kali isntallation and "mini_racer"

### ISSUE THREAD

**Issue by WladGold** [dradis/dradis-ce#977]
If you have issues with your installation and get an error like:
An error occurred while installing "mini_race"

You can fix it via a change in the GemFile:
change:
**gem 'mini_racer', "~> 0.4.0"**

**Comment by MattBudz** [comment]
Thanks @WladGold. 

We have already merged the mini_racer upgrade. PR for reference: https://github.com/dradis/dradis-ce/pull/970.

This will be included in the next release.
