### ISSUE TITLE
The tag v4.2.0 is on an older commit than the tag v4.1.2

### ISSUE THREAD

**Issue by sbrun** [dradis/dradis-ce#996]
### Steps to reproduce 
I wanted to update dradis in Kali. But after downloading the v4.2.0.tar.gz I noticed that something was wrong with the versions mentioned in the Gemfile* and in the CHANGELOG.
The tag v4.2.0 is on a commit dated 29th November 2021. But the tag v4.1.2 is on a commit dated 23th december 2021.

### System configuration
**Dradis version**: 4.2.0

**Comment by brianp** [comment]
Hey @sbrun thanks for pointing that out. It looks like the tag was just created at the wrong point in the history. I've adjust that tag to accurately reflect the release of 4.2.0. Try re-downloading and let us know how it goes.

**Comment by sbrun** [comment]
It's fixed. Thanks!
